### ISSUE TITLE
Congrats~~

### ISSUE THREAD

**Issue by Shad0wSeven** [seanboe/SimpleFusion#2]
## Not an issue, but congrats on getting accepted!!!!!

*you can delete this whenever you want lol its not a real issue*

![blobheart](https://cdn.discordapp.com/emojis/575100512333070339.png?size=64)

**Comment by seanboe** [comment]
https://camo.githubusercontent.com/a9265edca5df934261fc22244e3a71f85ac38065ba5764133ed6249800225fc9/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3537353130303531323333333037303333392e706e673f73697a653d3634

**Comment by seanboe** [comment]
🤗
